### PR TITLE
support Arrow on 1.9+ via pkg extension

### PR DESCRIPTION
**Pull request by palday**

### CODE REVIEW

**Review by quinnj — APPROVED** [review]
This conceptually looks good to me; some 1.6 tests are failing, however, so I think we either need to add a Requires.jl-based compat or bump up the Julia version; I don't have a real strong preference, though I'm a bit hazy on if 1.9 was declared a new LTS or not. Or is the plan for 1.10 to be an LTS? In either case, this package is currently "slow enough" that even bumping the version up to 1.9 doesn't seem terrible because I don't think there would be a ton of new features or bugfixes that we'd have to try and port back to older versions.

**Comment by iamed2** [comment]
@palday I'm concerned about the Beacon-internal impact of requiring 1.9 here actually. Let's confirm before merging this that that's okay.

**Comment by DilumAluthge** [comment]
Instead of dropping support for old Julia versions, why not just gate this particular Arrow functionality behind a `if Base.VERSION >= v"1.9-"`? So then JSON3 will still be usable on old Julia versions, but the Arrow functionality will only be available on Julia 1.9 and later.

**Comment by palday** [comment]
@quinnj gentle bump 🖤

**Pull request merged**
