### PR TITLE
Add singleton support

### PR DESCRIPTION
**Pull request by Wynand**
~~Depends on https://github.com/JuliaData/StructTypes.jl/pull/66~~

Adds support for writing Singletons

### CODE REVIEW

**Comment by iamed2** [comment]
@quinnj Any thoughts on this approach? This seems to have less impact than https://github.com/JuliaData/StructTypes.jl/pull/66 since it only replaces error behaviour and only for JSON3 and not the whole StructTypes-using ecosystem.

**Review by quinnj — APPROVED** [review]

**Comment by quinnj** [comment]
I think we need to bump the minimum StructTypes compat to `1.10`

**Comment by Wynand** [comment]
> I think we need to bump the minimum StructTypes compat to `1.10`

Bumped!

**Comment by Wynand** [comment]
I thought I saw a comment on here asking why a string is used instead of an empty object

My reasoning for that was that using a string still represents what the singleton is in some way, whereas with an empty object you wouldn't know what the singleton was

**Pull request merged**
